openapi: 3.0.0
info:
  title: API de Usuários
  version: 1.0.0

paths:
  /api/users:
    post:
      summary: Cria um novo usuário
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                idade:
                  type: integer
              required:
                - nome
                - email
                - idade
      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Dados inválidos
    get:
      summary: Lista usuários com paginação
      tags:
        - Usuários
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Página atual (default 1)
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Quantidade por página (default 10)
      responses:
        200:
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
  /api/users/{id}:
    put:
      summary: Edita um usuário
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                idade:
                  type: integer
              required:
                - nome
                - email
                - idade
      responses:
        200:
          description: Usuário editado com sucesso
    delete:
      summary: Exclui um usuário
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Usuário excluído com sucesso
    get:
      summary: Busca um usuário pelo ID
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Usuário não encontrado
  /api/users/batch:
    post:
      summary: Importa usuários em lote via arquivo CSV
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Arquivo CSV contendo os usuários (nome, email, idade)
      responses:
        200:
          description: Resultado da importação em lote
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  total:
                    type: integer
                  successCount:
                    type: integer
                  errorCount:
                    type: integer
        400:
          description: Arquivo CSV não enviado ou inválido

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
        idade:
          type: integer